// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDo.Backend.Data;

#nullable disable

namespace ToDo.Backend.Data.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20251024104634_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDo.Backend.Data.Model.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("todo_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 10, 46, 34, 15, DateTimeKind.Utc).AddTicks(4622),
                            Description = "Opis 1",
                            IsCompleted = false,
                            Title = "Zadanie 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 10, 46, 34, 15, DateTimeKind.Utc).AddTicks(4654),
                            Description = "Opis 2",
                            IsCompleted = true,
                            Title = "Zadanie 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 10, 46, 34, 15, DateTimeKind.Utc).AddTicks(4655),
                            Description = "Opis 3",
                            IsCompleted = false,
                            Title = "Zadanie 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 10, 46, 34, 15, DateTimeKind.Utc).AddTicks(4656),
                            Description = "Opis 4",
                            IsCompleted = false,
                            Title = "Zadanie 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 24, 10, 46, 34, 15, DateTimeKind.Utc).AddTicks(4657),
                            Description = "Opis 5",
                            IsCompleted = true,
                            Title = "Zadanie 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 24, 10, 46, 34, 15, DateTimeKind.Utc).AddTicks(4658),
                            Description = "Opis 6",
                            IsCompleted = false,
                            Title = "Zadanie 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
